[package]
name = "rong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6" }
heron = { version = "2.4.1", features = ["2d"] }

[features]
dev = [
    "bevy/dynamic",
]